#!/usr/bin/env bash

# i don't really need stow since the -f options delete if already exist :D
ln -n -f -s ~/dotfiles/scripts/ ~/.local/scripts

ln -n -f -s ~/dotfiles/wallpapers/ ~/wallpapers

ln -n -f -s ~/dotfiles/nvim ~/.config/nvim
ln -n -f -s ~/dotfiles/tmux ~/.config/tmux
ln -n -f -s ~/dotfiles/wezterm ~/.config/wezterm
ln -n -f -s ~/dotfiles/fish ~/.config/fish
ln -n -f -s ~/dotfiles/fish ~/.config/fish
ln -n -f -s ~/dotfiles/keyd ~/.config/keyd
